const dbRutas = [
    {
        id: "1",
        category: "sitios-web",
        linkHref: "sitios-web.html",
        targetType: "",
        imgSrc: "../public/images/sitios-web.png",
        titleH2: "Sitios Web Oficiales con cursos online",
        titleH3: "",
        contents: "",
        group: [
            {
                linkHref: "../page/w3schools.html",
                targetType: "",
                imgSrc: "../public/images/sitios-web/w3schools.jpg",
                titleH2: "W3Schools",
                titleH3: "",
                contents: "",
                linkCodeR11: "",
                cursos: [
                    {
                        linkHref: "https://www.w3schools.com/html/default.asp",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/html.jpg",
                        titleH2: "Curso HTML",
                        titleH3: "W3Schools",
                        contents: "HTML es el lenguaje de marcado estándar para las páginas web.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.w3schools.com/css/default.asp",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/css.jpg",
                        titleH2: "Curso CSS",
                        titleH3: "W3Schools",
                        contents: "CSS es el lenguaje para diseñar y maquetar una página web.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.w3schools.com/js/default.asp",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/javascript.jpg",
                        titleH2: "Curso JavaScript",
                        titleH3: "W3Schools",
                        contents: "Aprende el lenguaje de programación de la web más popular del mundo.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.w3schools.com/js/js_json_intro.asp",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/javascript.jpg",
                        titleH2: "JSON",
                        titleH3: "W3Schools",
                        contents: "JSON (Java Script Object Notation) es un formato de texto para almacenar y transportar datos. Además es autodescriptivo y fácil de entender",
                        linkCodeR11: "",
                    },
                ],
            },
            {
                linkHref: "../page/mdn.html",
                targetType: "",
                imgSrc: "../public/images/sitios-web/mdn-web-docs.jpg",
                titleH2: "MDN Web Docs",
                titleH3: "",
                contents: "",
                linkCodeR11: "",
                cursos: [
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/Getting_started_with_the_web",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/mdn-web-docs.jpg",
                        titleH2: "Introducción práctica al desarrollo de la web",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/HTML",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/html.jpg",
                        titleH2: "Semántica y estructura con HTML",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/CSS",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/css.jpg",
                        titleH2: "Estilo y diseño con CSS",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/JavaScript",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/javascript.jpg",
                        titleH2: "Interactividad con JavaScript",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/Forms",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/mdn-web-docs.jpg",
                        titleH2: "Formularios web",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/Accessibility",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/mdn-web-docs.jpg",
                        titleH2: "Hacer que la web funcione para todos",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/Tools_and_testing",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/github.jpg",
                        titleH2: "Herramientas modernas",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/Performance",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/mdn-web-docs.jpg",
                        titleH2: "Rendimiento web",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/Server-side",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/nodejs.jpg",
                        titleH2: "Programación del lado servidor",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                ],
            },
            {
                linkHref: "../page/microsoft.html",
                targetType: "",
                imgSrc: "../public/images/sitios-web/microsoft.jpg",
                titleH2: "Microsoft",
                titleH3: "",
                contents: "",
                linkCodeR11: "",
                cursos: [
                    {
                        linkHref: "https://docs.microsoft.com/es-es/learn/paths/web-development-101/",
                        imgSrc: "https://mpng.subpng.com/20180806/swf/kisspng-logo-microsoft-corporation-brand-windows-server-20-5b6885e2de9281.4204193815335766749117.jpg",
                        titleH2: "Desarrollo web para principiantes",
                        titleH3: "Microsoft",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://docs.microsoft.com/es-es/learn/modules/build-simple-website/",
                        imgSrc: "https://mpng.subpng.com/20180806/swf/kisspng-logo-microsoft-corporation-brand-windows-server-20-5b6885e2de9281.4204193815335766749117.jpg",
                        titleH2: "Creación de un sitio web sencillo con HTML, CSS y JavaScript",
                        titleH3: "Microsoft",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "http://127.0.0.1:5500/page/cursos-basicos.html",
                        imgSrc: "https://mpng.subpng.com/20180806/swf/kisspng-logo-microsoft-corporation-brand-windows-server-20-5b6885e2de9281.4204193815335766749117.jpg",
                        titleH2: "Ruta de Aprendizaje de GitHub",
                        titleH3: "Microsoft",
                        contents: "",
                        linkCodeR11: "",
                    },
                ],
            },
            {
                linkHref: "../page/w3c.html",
                targetType: "",
                imgSrc: "../public/images/sitios-web/w3c.jpg",
                titleH2: "W3Cx",
                titleH3: "",
                contents: "",
                linkCodeR11: "",
                cursos: [
                    {
                        linkHref: "https://www.edx.org/course/html5-and-css-fundamentals",
                        targetType: "_blank",
                        imgSrc: "https://w3cx.org/img/5-0-small.png",
                        titleH2: "HTML5 & CSS Fundamentals",
                        titleH3: "W3Cx",
                        contents: "Idioma: Inglés. Duración 6 Semanas. Nivel: Introductorio. Aprenda a crear sitios web utilizando HTML5 y CSS básico, directamente desde W3C, creador de los últimos estándares web.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.edx.org/course/web-accessibility-introduction",
                        targetType: "_blank",
                        imgSrc: "https://prod-discovery.edx-cdn.org/media/course/image/8ac6f7ff-0ff9-4894-a5f3-cc34fc5768fa-8357c71f5fa0.small.png",
                        titleH2: "Introduction to Web Accessibility",
                        titleH3: "W3Cx",
                        contents: "Introducción a la Accesibilidad Web. Obtén una base sólida en accesibilidad digital para que tus sitios web y aplicaciones funcionen bien y cumplan con los estándares internacionales.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.edx.org/course/javascript-introduction",
                        targetType: "_blank",
                        imgSrc: "https://prod-discovery.edx-cdn.org/media/course/image/c50943b5-3375-4d50-9f91-911930551603-5703bb2a02c8.small.png",
                        titleH2: "JavaScript Introduction",
                        titleH3: "W3Cx",
                        contents: "Aprenda JavaScript, un lenguaje de programación de desarrollo web, para agregar interactividad a sus páginas web y convertirse en un desarrollador web experto.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.edx.org/course/css-basics",
                        targetType: "_blank",
                        imgSrc: "https://prod-discovery.edx-cdn.org/media/course/image/32f1ba67-31e7-4b85-aa65-a4687036231c-80139b7286a9.small.png",
                        titleH2: "CSS Basics",
                        titleH3: "W3Cx",
                        contents: "Aprenda cómo llevar sus páginas web de suaves a audaces con el poder del estilo CSS.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.edx.org/course/html5-apps-and-games",
                        targetType: "_blank",
                        imgSrc: "https://prod-discovery.edx-cdn.org/media/course/image/6d40d803-76af-452b-8609-0dbadbe37fee-1577921cd54a.small.jpg",
                        titleH2: "HTML5 Apps and Games",
                        titleH3: "W3Cx",
                        contents: "Hoy en día, los desarrolladores están pasando cada vez más de aplicaciones nativas a aplicaciones basadas en HTML5. ¡Aumente su capacidad para diseñar y ofrecer servicios innovadores en la Web!",
                        linkCodeR11: "",
                    },

                ],
            },
            {
                linkHref: "https://platzi.com/cursos/programacion-basica-nuevo/",
                targetType: "_blank",
                imgSrc: "../public/images/sitios-web/platzi.jpg",
                titleH2: "Platzi",
                titleH3: "",
                contents: "",
                linkCodeR11: "",
                cursos: [
                    {
                        linkHref: "https://platzi.com/cursos/programacion-basica-nuevo/",
                        targetType: "_blank",
                        imgSrc: "https://static.platzi.com/cdn-cgi/image/width=1024,quality=50,format=auto/media/achievements/badge-piezas-programacion-basica-ede320eb-b1a9-4f1c-8b61-dd0502bbe4d3.png",
                        titleH2: "Nuevo Curso Gratis de Programación Básica",
                        titleH3: "Platzi",
                        contents: "Programa desde cero, domina Javascript, entiende HTML y aprende de algoritmos. Sí, desde cero. Entenderás la lógica del código, cómo piensan las programadoras expertas y cómo programar un videojuego web de principio a fin. Aprender a programar no es fácil, pero Platzi lo hace efectivo.",
                        linkCodeR11: "",
                    },
                ],
            },
            {
                linkHref: "../page/codecademy.html",
                targetType: "",
                imgSrc: "../public/images/sitios-web/codecademy.jpg",
                titleH2: "Codecademy",
                titleH3: "",
                contents: "",
                linkCodeR11: "",
                cursos: [
                    {
                        linkHref: "https://www.codecademy.com/learn/learn-html",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/html.jpg",
                        titleH2: "Learn HTML",
                        titleH3: "Codecademy",
                        contents: "Aprenda los conceptos básicos de HTML5 y comience a crear y editar páginas web.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.codecademy.com/learn/learn-css",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/css.jpg",
                        titleH2: "Learn CSS",
                        titleH3: "Codecademy",
                        contents: "Aprenda a diseñar y organizar visualmente HTML con CSS.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.codecademy.com/learn/introduction-to-javascript",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/javascript.jpg",
                        titleH2: "Learn JavaScript",
                        titleH3: "Codecademy",
                        contents: "Aprenda los fundamentos de JavaScript que necesitará para el desarrollo front-end o back-end.",
                        linkCodeR11: "",
                    },
                ],
            },
            {
                linkHref: "https://egghead.io/courses/the-beginner-s-guide-to-react",
                targetType: "_blank",
                imgSrc: "../public/images/sitios-web/egghead-io.jpg",
                titleH2: "egghead.io",
                titleH3: "",
                contents: "",
                linkCodeR11: "",
                cursos: [
                    {
                        linkHref: "https://egghead.io/courses/the-beginner-s-guide-to-react",
                        targetType: "_blank",
                        imgSrc: "../public/images/sitios-web/egghead-io.jpg",
                        titleH2: "The Beginner's Guide to React",
                        titleH3: "egghead.io",
                        contents: "React got that name for a reason. It’s a component-based JavaScript library that renders smartly and can seriously simplify your work. This course is for React newbies and anyone looking to build a solid foundation. It’s designed to teach you everything you need to start building web applications in React right away.",
                        linkCodeR11: "",
                    }
                ],
            },
            {
                linkHref: "https://www.edx.org/course/introduction-computer-science-harvardx-cs50x",
                targetType: "_blank",
                imgSrc: "../public/images/sitios-web/cs50-harvard.jpg",
                titleH2: "CS50 Harvard.Edu",
                titleH3: "",
                contents: "",
                linkCodeR11: "https://cs50.harvard.edu/x/2022/",
                cursos: [
                    {
                        linkHref: "",
                        targetType: "",
                        imgSrc: "",
                        titleH2: "Introducción a la informática de CS50",
                        titleH3: "CS50 Harvard.edu",
                        contents: "Los temas incluyen abstracción, algoritmos, estructuras de datos, encapsulación, administración de recursos, seguridad, ingeniería de software y desarrollo web. Los lenguajes incluyen C, Python, SQL y JavaScript, además de CSS y HTML.",
                        linkCodeR11: "",
                    }
                ],
            },
            {
                linkHref: "../page/web-dev.html",
                targetType: "",
                imgSrc: "../public/images/sitios-web/web-dev-google-developers.jpg",
                titleH2: "Web Dev",
                titleH3: "Google Developers",
                contents: "",
                linkCodeR11: "",
                cursos: [
                    {
                        linkHref: "https://web.dev/learn/forms/",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/wev-dev-formularios.jpg",
                        titleH2: "Aprender formularios",
                        titleH3: "Web Dev | Google Developers",
                        contents: "Un curso sobre formularios HTML para ayudarlo a mejorar su experiencia como desarrollador web.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://web.dev/learn/css/",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/wev-dev-fundamentos-css.jpg",
                        titleH2: "Aprender CSS",
                        titleH3: "Web Dev | Google Developers",
                        contents: "Un curso permanente de CSS y un modelo para mejorar sus conocimientos sobre el diseño de páginas web.",
                        linkCodeR11: "",
                    },                    
                    {
                        linkHref: "https://web.dev/learn/design/",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/wev-dev-responsive-design.jpg",
                        titleH2: "Aprende Responsive Design",
                        titleH3: "Web Dev | Google Developers",
                        contents: "Un curso que explora todos los aspectos del diseño responsive. Aprenda a crear sitios que se vean geniales y funcionen bien para todos.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://web.dev/learn/pwa/",
                        targetType: "_blank",
                        imgSrc: "../public/images/app/wev-dev-progressive-web-apps.jpg",
                        titleH2: "Aprende PWA (Progressive Web Apps)",
                        titleH3: "Web Dev | Google Developers",
                        contents: "Un curso que analiza todos los aspectos del desarrollo moderno de aplicaciones web progresivas.",
                        linkCodeR11: "",
                    },
                ],
            },

        ]
    },
    {
        id: "2",
        category: "documentacion-oficial",
        linkHref: "../page/documentacion.html",
        targetType: "",
        imgSrc: "../public/images/documentacionOficial.png",
        titleH2: "Documentación Oficial",
        titleH3: "",
        contents: "",
        group: [
            {
                linkHref: "https://html.spec.whatwg.org/multipage/",
                targetType: "_blank",
                imgSrc: "../public/images/app/html.jpg",
                titleH2: "HTML",
                titleH3: "WHATWG",
                contents: "La familiaridad con los conceptos básicos de DOM es necesaria para una comprensión completa de algunas de las partes más técnicas de esta especificación.",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "https://developer.mozilla.org/en-US/docs/Web/HTML",
                targetType: "_blank",
                imgSrc: "../public/images/app/html.jpg",
                titleH2: "HTML",
                titleH3: "MDN Web Docs",
                contents: "Referencia HTML: Hipertexto se refiere a enlaces que conectan páginas web entre sí, ya sea dentro de un solo sitio web o entre sitios web. Los enlaces son un aspecto fundamental de la Web.",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "https://www.w3.org/TR/CSS/",
                targetType: "_blank",
                imgSrc: "../public/images/app/css.jpg",
                titleH2: "CSS",
                titleH3: "W3.org",
                contents: "Este documento recopila en una sola definición todas las especificaciones que juntas forman el estado actual de las hojas de estilo en cascada (CSS) a partir de 2021.",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "https://developer.mozilla.org/en-US/docs/Web/CSS/Reference",
                targetType: "_blank",
                imgSrc: "../public/images/app/css.jpg",
                titleH2: "CSS",
                titleH3: "MDN Web Docs",
                contents: "Todas las propiedades CSS estándar, pseudoclases, pseudoelementos, tipos de datos, notaciones funcionales y reglas at. Conceptos clave de CSS y una lista de selectores organizados por tipo. Breve referencia de DOM-CSS/CSSOM.",
                linkCodeR11: "",
                cursos: [],
            },
        ],
    },
    {
        id: "3",
        category: "libros",
        linkHref: "../page/libros.html",
        targetType: "",
        imgSrc: "../public/images/librosWebDeveloper.png",
        titleH2: "Libros y Guias",
        titleH3: "",
        contents: "",
        group: []
    },
    {
        id: "4",
        category: "herramientas",
        linkHref: "../page/herramientas.html",
        targetType: "",
        imgSrc: "../public/images/herramientasWebDeveloper.png",
        titleH2: "Herramientas",
        titleH3: "",
        contents: "",
        group: [
            {
                linkHref: "../page/visual-studio-code.html",
                targetType: "",
                imgSrc: "../public/images/app/visual-studio-code.jpg",
                titleH2: "Visual Studio Code",
                titleH3: "Editor de Código y extensiones",
                contents: "",
                linkCodeR11: "",
                cursos : [
                    {
                        linkHref: "https://code.visualstudio.com",
                        imgSrc: "../public/images/app/vs-code.jpg",
                        titleH2: "Visual Studio Code",
                        titleH3: "Editor de código abierto para desarrolladores web",
                        contents: "Visual Studio Code es un editor de codificación gratuito que lo ayuda a comenzar a codificar rápidamente. ",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-es",
                        imgSrc: "https://ms-ceintl.gallerycdn.vsassets.io/extensions/ms-ceintl/vscode-language-pack-es/1.70.8100917/1660123424009/Microsoft.VisualStudio.Services.Icons.Default",
                        titleH2: "Microsoft | Spanish Language Pack for Visual Studio Code",
                        titleH3: "Paquete de idioma español para VS Code",
                        contents: "El paquete de idioma español proporciona una experiencia de UI localizada para VS Code.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://marketplace.visualstudio.com/items?itemName=EliverLara.andromeda",
                        imgSrc: "https://eliverlara.gallerycdn.vsassets.io/extensions/eliverlara/andromeda/1.7.1/1652738880846/Microsoft.VisualStudio.Services.Icons.Default",
                        titleH2: "Andromeda",
                        titleH3: "Eliver Lara | Tema oscuro con sabor a universo.",
                        contents: "¡La combinación de colores es simplemente increíble!",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer",
                        imgSrc: "https://ritwickdey.gallerycdn.vsassets.io/extensions/ritwickdey/liveserver/5.7.5/1646738284779/Microsoft.VisualStudio.Services.Icons.Default",
                        titleH2: "Live Server",
                        titleH3: "Ritwick Dey | Servidor en vivo",
                        contents: "Inicie un servidor local de desarrollo con función de recarga en vivo para páginas estáticas y dinámicas",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner",
                        imgSrc: "../public/images/app/run.jpg",
                        titleH2: "Code Runner",
                        titleH3: "junio han | Ejecutar un código",
                        contents: "Ejecute un fragmento de código o un archivo de código para varios idiomas",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint",
                        imgSrc: "https://dbaeumer.gallerycdn.vsassets.io/extensions/dbaeumer/vscode-eslint/2.2.6/1657015175302/Microsoft.VisualStudio.Services.Icons.Default",
                        titleH2: "ESLint",
                        titleH3: "Microsoft | Integra ESLint JavaScript en VS Code",
                        contents: "Permite integrar ESLint dentro de VSCode. Con la configuración previa dentro del proyecto, detecta errores en tiempo de desarrollo.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens",
                        imgSrc: "https://usernamehw.gallerycdn.vsassets.io/extensions/usernamehw/errorlens/3.6.0/1658612570729/Microsoft.VisualStudio.Services.Icons.Default",
                        titleH2: "Error Lens",
                        titleH3: "Alexander | Resaltar errores",
                        contents: "Mejora el resaltado de errores, advertencias y otros diagnósticos lingüísticos.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag",
                        imgSrc: "../public/images/app/auto-rename-t-ag.jpg",
                        titleH2: "Auto Rename Tag",
                        titleH3: "Jun Han | Renombrar Elementos",
                        contents: "Cambio automático de nombre de etiqueta emparejada HTML/XML",
                        linkCodeR11: "",
                    },
                    /* {
                        linkHref: "",
                        imgSrc: "",
                        titleH2: "",
                        titleH3: "",
                        contents: "",
                        linkCodeR11: "",
                    }, */
                ]
            },
            {
                linkHref: "https://nodejs.org/es/",
                targetType: "_blank",
                imgSrc: "../public/images/app/nodejs.jpg",
                titleH2: "Node.JS",
                titleH3: "Entorno de ejecución para JavaScript",
                contents: "",
                linkCodeR11: "",
            },
            {
                linkHref: "https://fonts.google.com/",
                targetType: "_blank",
                imgSrc: "../public/images/app/google-fonts.jpg",
                titleH2: "Google Fonts",
                titleH3: "Biblioteca de 1442 familias de fuentes de código abierto y API",
                contents: "Google Fonts es una biblioteca de 1442 familias de fuentes de código abierto y API para un uso conveniente a través de CSS y Android.",
                linkCodeR11: "",
            },
            {
                linkHref: "https://roadmap.sh/frontend",
                targetType: "_blank",
                imgSrc: "../public/images/app/roadmap-SH.jpg",
                titleH2: "Roadmap SH",
                titleH3: "Desarrollador front-end",
                contents: "Guía paso a paso para convertirse en un desarrollador frontend moderno en 2022",
                linkCodeR11: "",
            },
        ]
    },
    {
        id: "5",
        category: "sand-box",
        linkHref: "../page/sand-box.html",
        targetType: "",
        imgSrc: "../public/images/sandBoxWebDeveloper.png",
        titleH2: "Sand-Box: Prueba, Aprende y Desarrolla",
        titleH3: "",
        contents: "",
        notas: "Prácticas y ejercicios para probar, aprender y desarrolla tu lógica de Programación",
        group: [
            {
                linkHref: "https://www.codewars.com/",
                targetType: "_blank",
                imgSrc: "../public/images/app/codewars.jpg",
                titleH2: "CodeWars",
                titleH3: "Entrena y mejora tus habilidades de codificación",
                contents: "Aprende, entrena y mejora tus habilidades de codificación al resolver tareas de programación de muchos tipos y niveles de dificultad.",
                linkCodeR11: "",
            },
            {
                linkHref: "https://www.jshero.net/en/home.html",
                targetType: "_blank",
                imgSrc: "../public/images/app/js-hero.jpg",
                titleH2: "JavaScript Hero",
                titleH3: "Aprende a codificar con JS Hero con ejercicios interactivos.",
                contents: "Cuenta con un tutorial, prácticas y un patio de juego para experimentar con el código y mejorar nivel de programación en JavaScritp.",
                linkCodeR11: "",
            },
            {
                linkHref: "https://edabit.com/challenges",
                targetType: "_blank",
                imgSrc: "../public/images/app/edabit.jpg",
                titleH2: "Edabit",
                titleH3: "Práctica tu código y resuelve los retos",
                contents: "Aprende JavaScript y enfréntate a desafíos interactivos. Desarrolla tus habilidades y mejora tu rendimiento como programador.",
                linkCodeR11: "",
            },
        ]
    },
    {
        id: "6",
        category: "boot-camp",
        linkHref: "../page/boot-camp.html",
        targetType: "",
        imgSrc: "../public/images/bootCamp.png",
        titleH2: "Coding Bootcamp",
        titleH3: "",
        contents: "",
        group: [
            {
                linkHref: "https://fullstackopen.com/es/",
                targetType: "_blank",
                imgSrc: "../public/images/app/Full-Stack-Open.jpg",
                titleH2: "Full Stack Open",
                titleH3: "Profundización en el desarrollo web moderno",
                contents: "Este curso le presentará el desarrollo web moderno basado en JavaScript. Aprende a crear aplicaciones con ReactJS que usan REST API creadas con Node.js",
                linkCodeR11: "",
            },
            {
                linkHref: "https://www.youtube.com/playlist?list=PLV8x_i1fqBw0Kn_fBIZTa3wS_VZAqddX7",
                targetType: "_blank",
                imgSrc: "../public/images/app/midudev-Bootcamp-fullStack.jpg",
                titleH2: "Midudev Bootcamp FullStack",
                titleH3: "FullStack JavaScript Bootcamp totalmente gratis y desde cero.",
                contents: "55 Videos del canal de Midudev para el aprendizaje FullStack JavaScript.",
                linkCodeR11: "",
            },
        ]
    },
    {
        id: "7",
        category: "mentores",
        linkHref: "../page/mentores.html",
        targetType: "",
        imgSrc: "../public/images/mentoresWebDeveloper.png",
        titleH2: "Guía de Expertos",
        titleH3: "",
        contents: "",
        group: [
            {
                linkHref: "https://www.youtube.com/c/midudev",
                targetType: "_blank",
                imgSrc: "https://yt3.ggpht.com/ytc/AKedOLTBFvOrff69Sw8UxdRsEF5ABUpNZpxfmm86VNZZgQ=s176-c-k-c0x00ffffff-no-rj",
                titleH2: "Miguel Ángel Duran",
                titleH3: "Midudev",
                contents: "<a href='https://midu.dev/' target='_blank'>Web</a> <br>Desarrollo con JavaScript. Programación web y FULL STACK con React, Node.js, HTML, CSS, Tailwind, Next.js y Deno.",
                linkCodeR11: "",
            },
            {
                linkHref: "https://www.youtube.com/c/HolaMundoDev",
                targetType: "_blank",
                imgSrc: "https://yt3.ggpht.com/Z69fhRL9_OaXsDz-XsCUe2sGIqU7G1F5Mwl0PwlBsx_ll13K0nLb47q7_RMen7NHvzMVDgd2=s176-c-k-c0x00ffffff-no-rj",
                titleH2: "Nicolas Schurmann",
                titleH3: "Hola Mundo",
                contents: "<a href='https://www.nicolas-schurmann.com/' target='_blank'>Web</a> <br>Educación académica para desarrolladores del mundo de habla hispana, con capacitaciones de alto nivel, de lo más básico hasta lo más avanzado.",
                linkCodeR11: "",
            },
            {
                linkHref: "https://www.youtube.com/c/GonzaloPozzo",
                targetType: "_blank",
                imgSrc: "https://yt3.ggpht.com/LJFbfHUSHXK89JMeG-XhOoE24MS2oiWbs_h_UHgOSvs5SOSaeArCXK9YvyiVh48YI_5CGZz55Wg=s176-c-k-c0x00ffffff-no-rj",
                titleH2: "Gonzalo Pozzo",
                titleH3: "Gonzalo Pozzo | Goncy",
                contents: "<a href='https://goncy.netlify.app/' target='_blank'>Web</a> <br>Desarrollador frontend @Vercel que trabaja con React - Redux stack, Cypress.io Ambassador. Co-organizador @freeCodeCampBA , ayudando a las personas a obtener su primer trabajo de TI, nunca dejé de aprender.",
                linkCodeR11: "",
            },
            {
                linkHref: "https://www.youtube.com/c/FaztTech",
                targetType: "_blank",
                imgSrc: "https://yt3.ggpht.com/ytc/AKedOLSggvA4usmC3lIDdqORkmsje78sxwaSPsQ3gefNYw=s176-c-k-c0x00ffffff-no-rj",
                titleH2: "Fazt",
                titleH3: "Fazt",
                contents: "<a href='https://www.faztweb.com/' target='_blank'>Web</a><br>Todo lo que siempre quisiste saber sobre programación web y nunca te atreviste a preguntar.",
                linkCodeR11: "",
            },
            {
                linkHref: "https://www.youtube.com/c/FalconMasters",
                targetType: "_blank",
                imgSrc: "https://yt3.ggpht.com/ytc/AKedOLSZnvHT0zdGfJpGB1MH1gd6K4JlqFpv3PE0rqJ6=s176-c-k-c0x00ffffff-no-rj",
                titleH2: "Carlos Arturo",
                titleH3: "FalconMasters",
                contents: "<a href='http://www.falconmasters.com/' target='_blank'>Web</a><br>YouTuber, Diseñador Web, Geek y Emprendedor",
                linkCodeR11: "",
            },
            {
                linkHref: "https://www.youtube.com/c/ColtSteeleCode",
                targetType: "_blank",
                imgSrc: "https://yt3.ggpht.com/ytc/AMLnZu88ZkiZWoGwvsiYfeELj7youSFcFtbRIjn3Sivv=s176-c-k-c0x00ffffff-no-rj",
                titleH2: "Colt Steele",
                titleH3: "Colt Steele",
                contents: "",
                linkCodeR11: "",
            },

        ]
    },
    {
        id: "8",
        category: "videos-tutoriales",
        linkHref: "../page/videos.html",
        targetType: "",
        imgSrc: "../public/images/video-tutoriales.png",
        titleH2: "Tutoriales y Cursos en Youtube",
        titleH3: "",
        contents: "",
        group: [
            {
                linkHref: "../page/videos-html.html",
                targetType: "",
                imgSrc: "../public/images/app/html.jpg",
                titleH2: "HTML",
                titleH3: "Video Tutoriales",
                contents: "Aprende HTML",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "../page/videos-css.html",
                targetType: "",
                imgSrc: "../public/images/app/css.jpg",
                titleH2: "CSS",
                titleH3: "Video Tutoriales",
                contents: "Aprende CSS",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "../page/videos-javascript.html",
                targetType: "",
                imgSrc: "../public/images/app/javascript.jpg",
                titleH2: "JavaScript",
                titleH3: "Video Tutoriales",
                contents: "Aprende JavaScript",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "../page/videos-react.html",
                targetType: "",
                imgSrc: "../public/images/app/react.jpg",
                titleH2: "React",
                titleH3: "Video Tutoriales",
                contents: "Aprende React",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "../page/videos-todos.html",
                targetType: "",
                imgSrc: "../public/images/app/videos-todos.jpg",
                titleH2: "Todos los videos",
                titleH3: "Recopilatorio",
                contents: "Recopilatorio",
                linkCodeR11: "",
                cursos: [],
            },
        ]
    },
    {
        id: "9",
        category: "hosting",
        linkHref: "../page/hosting.html",
        targetType: "",
        imgSrc: "../public/images/webHosting.png",
        titleH2: "Dominios y Hospedajes Web",
        titleH3: "",
        contents: "",
        notas: "[squarespace.com]",
        group: [
            {
                linkHref: "https://pages.github.com/",
                targetType: "_blank",
                imgSrc: "../public/images/app/github-pages.jpg",
                titleH2: "GitHub Pages",
                titleH3: "Sitios web para ti y tus proyectos",
                contents: "Alojado directamente desde su repositorio de GitHub . Simplemente edite, presione y sus cambios estarán en vivo.",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "https://www.w3schools.com/spaces/",
                targetType: "_blank",
                imgSrc: "../public/images/app/w3schools-spaces.jpg",
                titleH2: "W3Schools Spaces",
                titleH3: "Utiliza W3Schools Spaces para crear tu propio sitio web profesional.",
                contents: "W3Schools proporciona W3Schools Spaces para alojar su sitio web estático. Con Spaces, puede alojar fácilmente su sitio web con unos pocos clics.",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "https://vercel.com/dashboard",
                targetType: "_blank",
                imgSrc: "../public/images/app/vercel-hosting.jpg",
                titleH2: "Vercel",
                titleH3: "Plataforma frontend y hosting",
                contents: "Vercel es una plataforma que brinda hosting gratis para tus páginas web estáticas. Tienen varios ejemplos, con los principales frameworks frontend javascript para que puedas crear tu proyecto from scratch.",
                linkCodeR11: "",
                cursos: [],
            },
        ]
    },
    {
        id: "10",
        category: "portafolio",
        linkHref: "../page/portafolio.html",
        targetType: "",
        imgSrc: "../public/images/portafolio-code-r11.png",
        titleH2: "Portafolio",
        titleH3: "",
        contents: "",
        nota: "Crea tu portafolio de una manera profesional.",
        group: [
            {
                linkHref: "https://www.w3schools.com/w3css/w3css_templates.asp",
                targetType: "_blank",
                imgSrc: "../public/images/app/w3schools-plantilla-portafolio.jpg",
                titleH2: "W3.CSS Website Templates",
                titleH3: "Plantillas responsive del sitio web W3.CSS",
                contents: "Eres libre de modificar, guardar, compartir estas plantillas y usar en todos tus proyectos.",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "https://vercel.com/templates/next.js/portfolio-starter-kit",
                targetType: "_blank",
                imgSrc: "../public/images/app/vercel-portafolio.jpg",
                titleH2: "Vercel",
                titleH3: "Plantilla para tu Portafolio",
                contents: "Este portafolio está construido con Next.js y una biblioteca llamada Nextra. Te permite escribir Markdown y concentrarte en el contenido de tu portafolio.",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "../page/videos-portafolios.html",
                targetType: "",
                imgSrc: "../public/images/app/videos-portafolio.jpg",
                titleH2: "Recomendaciones para Crear tu Portafolio",
                titleH3: "Videos",
                contents: "Consejos y recomendaciones para crear tu portafolio como desarrollador web.",
                linkCodeR11: "",
                cursos: [],
            },
        ]
    },
    {
        id: "11",
        category: "trabajos-remotos",
        linkHref: "trabajos-remotos.html",
        targetType: "",
        imgSrc: "../public/images/TrabajosRemotos.png",
        titleH2: "Proyectos y Trabajos Remotos",
        titleH3: "",
        contents: "",
        group: [
            {
                linkHref: "trabajos-remotos.html",
                targetType: "",
                imgSrc: "https://yt3.ggpht.com/dW6to0x5Crmeh7yi-YPLcQRqVrBtx2BSh8eoKTJbE8NbjloQ0sqlmdszIlxokJU_97-ndOt_=s900-c-k-c0x00ffffff-no-rj",
                titleH2: "ARC()",
                titleH3: "Inglés",
                contents: "Búsqueda de trabajo a distancia",
            },
            {
                linkHref: "trabajos-remotos.html",
                targetType: "",
                imgSrc: "https://miro.medium.com/max/1400/1*aTYOTFS4Vkr-nwHNML3GvQ.jpeg",
                titleH2: "Otra",
                titleH3: "Inglés",
                contents: "Búsqueda de trabajo a distanciadonde. ",
            }
        ]
    },
    {
        id: "12",
        category: "Code-R11",
        linkHref: "../page/proyecto-code-r11.html",
        targetType: "",
        imgSrc: "../public/images/coder11.jpg",
        titleH2: "Ruta de Aprendizaje y Plan de Estudio Code R11",
        titleH3: "",
        contents: "",
        group: []
    },
];



