const dbRutas = [
    {
        id: "1",
        category: "sitios-web",
        linkHref: "sitios-web.html",
        targetType : "",
        imgSrc: "../public/images/sitios-web.png",
        titleH2: "Sitios Web Oficiales con cursos online",
        titleH3: "",
        contents: "",
        group: [
            {
                linkHref: "../page/w3schools.html",
                targetType : "",
                imgSrc: "../public/images/sitios-web/w3schools.jpg",
                titleH2: "W3Schools",
                titleH3: "",
                contents: "",
                linkCodeR11: "",
                cursos: [
                    {
                        linkHref: "https://www.w3schools.com/html/default.asp",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/html.jpg",
                        titleH2: "Curso HTML",
                        titleH3: "W3Schools",
                        contents: "HTML es el lenguaje de marcado estándar para las páginas web.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.w3schools.com/css/default.asp",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/css.jpg",
                        titleH2: "Curso CSS",
                        titleH3: "W3Schools",
                        contents: "CSS es el lenguaje para diseñar y maquetar una página web.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.w3schools.com/js/default.asp",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/javascript.jpg",
                        titleH2: "Curso JavaScript",
                        titleH3: "W3Schools",
                        contents: "Aprende el lenguaje de programación de la web más popular del mundo.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.w3schools.com/js/js_json_intro.asp",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/javascript.jpg",
                        titleH2: "JSON",
                        titleH3: "W3Schools",
                        contents: "JSON (Java Script Object Notation) es un formato de texto para almacenar y transportar datos. Además es autodescriptivo y fácil de entender",
                        linkCodeR11: "",
                    },
                ],
            },
            {
                linkHref: "../page/mdn.html",
                targetType : "",
                imgSrc: "../public/images/sitios-web/mdn-web-docs.jpg",
                titleH2: "MDN Web Docs",
                titleH3: "",
                contents: "",
                linkCodeR11: "",
                cursos: [
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/Getting_started_with_the_web",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/mdn-web-docs.jpg",
                        titleH2: "Introducción práctica al desarrollo de la web",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/HTML",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/html.jpg",
                        titleH2: "Semántica y estructura con HTML",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/CSS",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/css.jpg",
                        titleH2: "Estilo y diseño con CSS",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/JavaScript",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/javascript.jpg",
                        titleH2: "Interactividad con JavaScript",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/Forms",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/mdn-web-docs.jpg",
                        titleH2: "Formularios web",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/Accessibility",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/mdn-web-docs.jpg",
                        titleH2: "Hacer que la web funcione para todos",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/Tools_and_testing",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/github.jpg",
                        titleH2: "Herramientas modernas",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/Performance",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/mdn-web-docs.jpg",
                        titleH2: "Rendimiento web",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://developer.mozilla.org/es/docs/Learn/Server-side",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/nodejs.jpg",
                        titleH2: "Programación del lado servidor",
                        titleH3: "MDN Web Docs",
                        contents: "",
                        linkCodeR11: "",
                    },
                ],
            },
            {
                linkHref: "../page/microsoft.html",
                targetType : "",
                imgSrc: "../public/images/sitios-web/microsoft.jpg",
                titleH2: "Microsoft",
                titleH3: "",
                contents: "",
                linkCodeR11: "",
                cursos: [
                    {
                        linkHref: "https://docs.microsoft.com/es-es/learn/paths/web-development-101/",
                        imgSrc: "https://mpng.subpng.com/20180806/swf/kisspng-logo-microsoft-corporation-brand-windows-server-20-5b6885e2de9281.4204193815335766749117.jpg",
                        titleH2: "Desarrollo web para principiantes",
                        titleH3: "Microsoft",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://docs.microsoft.com/es-es/learn/modules/build-simple-website/",
                        imgSrc: "https://mpng.subpng.com/20180806/swf/kisspng-logo-microsoft-corporation-brand-windows-server-20-5b6885e2de9281.4204193815335766749117.jpg",
                        titleH2: "Creación de un sitio web sencillo con HTML, CSS y JavaScript",
                        titleH3: "Microsoft",
                        contents: "",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "http://127.0.0.1:5500/page/cursos-basicos.html",
                        imgSrc: "https://mpng.subpng.com/20180806/swf/kisspng-logo-microsoft-corporation-brand-windows-server-20-5b6885e2de9281.4204193815335766749117.jpg",
                        titleH2: "Ruta de Aprendizaje de GitHub",
                        titleH3: "Microsoft",
                        contents: "",
                        linkCodeR11: "",
                    },
                ],
            },
            {
                linkHref: "../page/w3c.html",
                targetType : "",
                imgSrc: "../public/images/sitios-web/w3c.jpg",
                titleH2: "W3Cx",
                titleH3: "",
                contents: "",
                linkCodeR11: "",
                cursos: [
                    {
                        linkHref: "https://www.edx.org/course/html5-and-css-fundamentals",
                        targetType : "_blank",
                        imgSrc: "https://w3cx.org/img/5-0-small.png",
                        titleH2: "HTML5 & CSS Fundamentals",
                        titleH3: "W3Cx",
                        contents: "Idioma: Inglés. Duración 6 Semanas. Nivel: Introductorio. Aprenda a crear sitios web utilizando HTML5 y CSS básico, directamente desde W3C, creador de los últimos estándares web.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.edx.org/course/web-accessibility-introduction",
                        targetType : "_blank",
                        imgSrc: "https://prod-discovery.edx-cdn.org/media/course/image/8ac6f7ff-0ff9-4894-a5f3-cc34fc5768fa-8357c71f5fa0.small.png",
                        titleH2: "Introduction to Web Accessibility",
                        titleH3: "W3Cx",
                        contents: "Introducción a la Accesibilidad Web. Obtén una base sólida en accesibilidad digital para que tus sitios web y aplicaciones funcionen bien y cumplan con los estándares internacionales.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.edx.org/course/javascript-introduction",
                        targetType : "_blank",
                        imgSrc: "https://prod-discovery.edx-cdn.org/media/course/image/c50943b5-3375-4d50-9f91-911930551603-5703bb2a02c8.small.png",
                        titleH2: "JavaScript Introduction",
                        titleH3: "W3Cx",
                        contents: "Aprenda JavaScript, un lenguaje de programación de desarrollo web, para agregar interactividad a sus páginas web y convertirse en un desarrollador web experto.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.edx.org/course/css-basics",
                        targetType : "_blank",
                        imgSrc: "https://prod-discovery.edx-cdn.org/media/course/image/32f1ba67-31e7-4b85-aa65-a4687036231c-80139b7286a9.small.png",
                        titleH2: "CSS Basics",
                        titleH3: "W3Cx",
                        contents: "Aprenda cómo llevar sus páginas web de suaves a audaces con el poder del estilo CSS.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.edx.org/course/html5-apps-and-games",
                        targetType : "_blank",
                        imgSrc: "https://prod-discovery.edx-cdn.org/media/course/image/6d40d803-76af-452b-8609-0dbadbe37fee-1577921cd54a.small.jpg",
                        titleH2: "HTML5 Apps and Games",
                        titleH3: "W3Cx",
                        contents: "Hoy en día, los desarrolladores están pasando cada vez más de aplicaciones nativas a aplicaciones basadas en HTML5. ¡Aumente su capacidad para diseñar y ofrecer servicios innovadores en la Web!",
                        linkCodeR11: "",
                    },

                ],
            },
            {
                linkHref: "https://platzi.com/cursos/programacion-basica-nuevo/",
                targetType : "_blank",
                imgSrc: "../public/images/sitios-web/platzi.jpg",
                titleH2: "Platzi",
                titleH3: "",
                contents: "",
                linkCodeR11: "",
                cursos: [
                    {
                        linkHref: "https://platzi.com/cursos/programacion-basica-nuevo/",
                        targetType : "_blank",
                        imgSrc: "https://static.platzi.com/cdn-cgi/image/width=1024,quality=50,format=auto/media/achievements/badge-piezas-programacion-basica-ede320eb-b1a9-4f1c-8b61-dd0502bbe4d3.png",
                        titleH2: "Nuevo Curso Gratis de Programación Básica",
                        titleH3: "Platzi",
                        contents: "Programa desde cero, domina Javascript, entiende HTML y aprende de algoritmos. Sí, desde cero. Entenderás la lógica del código, cómo piensan las programadoras expertas y cómo programar un videojuego web de principio a fin. Aprender a programar no es fácil, pero Platzi lo hace efectivo.",
                        linkCodeR11: "",
                    },
                ],
            },
            {
                linkHref: "../page/codecademy.html",
                targetType : "",
                imgSrc: "../public/images/sitios-web/codecademy.jpg",
                titleH2: "Codecademy",
                titleH3: "",
                contents: "",
                linkCodeR11: "",
                cursos: [
                    {
                        linkHref: "https://www.codecademy.com/learn/learn-html",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/html.jpg",
                        titleH2: "Learn HTML",
                        titleH3: "Codecademy",
                        contents: "Aprenda los conceptos básicos de HTML5 y comience a crear y editar páginas web.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.codecademy.com/learn/learn-css",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/css.jpg",
                        titleH2: "Learn CSS",
                        titleH3: "Codecademy",
                        contents: "Aprenda a diseñar y organizar visualmente HTML con CSS.",
                        linkCodeR11: "",
                    },
                    {
                        linkHref: "https://www.codecademy.com/learn/introduction-to-javascript",
                        targetType : "_blank",
                        imgSrc: "../public/images/app/javascript.jpg",
                        titleH2: "Learn JavaScript",
                        titleH3: "Codecademy",
                        contents: "Aprenda los fundamentos de JavaScript que necesitará para el desarrollo front-end o back-end.",
                        linkCodeR11: "",
                    },
                ],
            }, 
            {
                linkHref: "https://egghead.io/courses/the-beginner-s-guide-to-react",
                targetType : "_blank",
                imgSrc: "../public/images/sitios-web/egghead-io.jpg",
                titleH2: "egghead.io",
                titleH3: "",
                contents: "",
                linkCodeR11: "",
                curso: [
                    {
                        linkHref: "https://egghead.io/courses/the-beginner-s-guide-to-react",
                        targetType : "_blank",
                        imgSrc: "../public/images/sitios-web/egghead-io.jpg",
                        titleH2: "The Beginner's Guide to React",
                        titleH3: "egghead.io",
                        contents: "React got that name for a reason. It’s a component-based JavaScript library that renders smartly and can seriously simplify your work. This course is for React newbies and anyone looking to build a solid foundation. It’s designed to teach you everything you need to start building web applications in React right away.",
                        linkCodeR11: "",
                    }
                ],
            },
            {
                linkHref: "https://www.edx.org/course/introduction-computer-science-harvardx-cs50x",
                targetType : "_blank",
                imgSrc: "../public/images/sitios-web/cs50-harvard.jpg",
                titleH2: "CS50 Harvard.Edu",
                titleH3: "",
                contents: "",
                linkCodeR11: "https://cs50.harvard.edu/x/2022/",
                curso: [
                    {
                        linkHref: "",
                        targetType : "",
                        imgSrc: "",
                        titleH2: "Introducción a la informática de CS50",
                        titleH3: "CS50 Harvard.edu",
                        contents: "Los temas incluyen abstracción, algoritmos, estructuras de datos, encapsulación, administración de recursos, seguridad, ingeniería de software y desarrollo web. Los lenguajes incluyen C, Python, SQL y JavaScript, además de CSS y HTML.",
                        linkCodeR11: "",
                    }
                ],
            },

        ]
    },
    {
        id: "2",
        category: "documentacion-oficial",
        linkHref: "../page/documentacion.html",
        targetType : "",
        imgSrc: "../public/images/documentacionOficial.png",
        titleH2: "Documentación Oficial",
        titleH3: "",
        contents: "",
        group: [
            {
                linkHref: "https://html.spec.whatwg.org/multipage/",
                targetType : "_blank",
                imgSrc: "../public/images/app/html.jpg",
                titleH2: "HTML",
                titleH3: "WHATWG",
                contents: "La familiaridad con los conceptos básicos de DOM es necesaria para una comprensión completa de algunas de las partes más técnicas de esta especificación.",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "https://developer.mozilla.org/en-US/docs/Web/HTML",
                targetType : "_blank",
                imgSrc: "../public/images/app/html.jpg",
                titleH2: "HTML",
                titleH3: "MDN Web Docs",
                contents: "Referencia HTML: Hipertexto se refiere a enlaces que conectan páginas web entre sí, ya sea dentro de un solo sitio web o entre sitios web. Los enlaces son un aspecto fundamental de la Web.",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "https://www.w3.org/TR/CSS/",
                targetType : "_blank",
                imgSrc: "../public/images/app/css.jpg",
                titleH2: "CSS",
                titleH3: "W3.org",
                contents: "Este documento recopila en una sola definición todas las especificaciones que juntas forman el estado actual de las hojas de estilo en cascada (CSS) a partir de 2021.",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "https://developer.mozilla.org/en-US/docs/Web/CSS/Reference",
                targetType : "_blank",
                imgSrc: "../public/images/app/css.jpg",
                titleH2: "CSS",
                titleH3: "MDN Web Docs",
                contents: "Todas las propiedades CSS estándar, pseudoclases, pseudoelementos, tipos de datos, notaciones funcionales y reglas at. Conceptos clave de CSS y una lista de selectores organizados por tipo. Breve referencia de DOM-CSS/CSSOM.",
                linkCodeR11: "",
                cursos: [],
            },
        ],
    },
    {
        id: "3",
        category: "libros",
        linkHref: "../page/libros.html",
        targetType : "",
        imgSrc: "../public/images/librosWebDeveloper.png",
        titleH2: "Libros y Guias",
        titleH3: "",
        contents: "",
        group: []
    },
    {
        id: "4",
        category: "Herramientas",
        linkHref: "",
        targetType : "",
        imgSrc: "../public/images/herramientasWebDeveloper.png",
        titleH2: "Herramientas",
        titleH3: "",
        contents: "",
        group: [
            {
                linkHref: "",
                targetType : "",
                imgSrc: "",
                titleH2: "Visual Studio Code",
                titleH3: "",
                contents: "",
            },
        ]
    },
    {
        id: "5",
        category: "Sand-Box",
        linkHref: "sand-box.html",
        targetType : "",
        imgSrc: "../public/images/sandBoxWebDeveloper.png",
        titleH2: "Sand-Box: Prueba, Aprende y Desarrolla",
        titleH3: "",
        contents: "",
        notas: "Prácticas y ejercicios para probar, aprender y desarrolla tu lógica de Programación",
        group: [
            {
                linkHref: "https://www.codewars.com/",
                targetType : "",
                imgSrc: "https://assets-global.website-files.com/62462834c60df92621c6b5be/62462c29f3165b55ea6255ea_light-text-logo-vertical.svg",
                titleH2: "Plataforma para Entrenar y Mejorar tus Habilidades de Codificación",
                titleH3: "CodeWars",
                contents: "Codewars es una plataforma que lo ayuda a aprender, entrenar y mejorar sus habilidades de codificación al resolver tareas de programación de muchos tipos y niveles de dificultad. Tú eliges cómo te gustaría aprender. ¿Quieres asumir desafíos cada vez más difíciles? Quizás prefieras entrenar a través de la repetición y mejorando tus soluciones. Después de resolver una tarea, compare su respuesta con la de otros usuarios y aprenda de ellos o ayude a los usuarios menos experimentados respondiendo a sus preguntas.",
            }
        ]
    },
    {
        id: "6",
        category: "Boot-Camp",
        linkHref: "",
        targetType : "",
        imgSrc: "../public/images/bootCamp.png",
        titleH2: "Coding Bootcamp",
        titleH3: "",
        contents: "",
        group: []
    },
    {
        id: "7",
        category: "Mentores-Canal-Youtube",
        linkHref: "https://www.w3schools.com/html/default.asp",
        targetType : "",
        imgSrc: "../public/images/mentoresWebDeveloper.png",
        titleH2: "Guía de Expertos en Youtube",
        titleH3: "",
        contents: "",
        group: []
    },
    {
        id: "8",
        category: "videos-tutoriales",
        linkHref: "../page/videos.html",
        targetType : "",
        imgSrc: "../public/images/video-tutoriales.png",
        titleH2: "Tutoriales y Cursos en Youtube",
        titleH3: "",
        contents: "",
        group: [
            {
                linkHref: "../page/videos-html.html",
                targetType : "",
                imgSrc: "../public/images/app/html.jpg",
                titleH2: "HTML",
                titleH3: "Video Tutoriales",
                contents: "Aprende HTML",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "../page/videos-css.html",
                targetType : "",
                imgSrc: "../public/images/app/css.jpg",
                titleH2: "CSS",
                titleH3: "Video Tutoriales",
                contents: "Aprende CSS",
                linkCodeR11: "",
                cursos: [],
            },
            {
                linkHref: "../page/videos-javascript.html",
                targetType : "",
                imgSrc: "../public/images/app/javascript.jpg",
                titleH2: "JavaScript",
                titleH3: "Video Tutoriales",
                contents: "Aprende JavaScript",
                linkCodeR11: "",
                cursos: [],
            },
        ]
    },
    {
        id: "9",
        category: "hospedaje-web",
        linkHref: "",
        targetType : "",
        imgSrc: "../public/images/webHosting.png",
        titleH2: "Dominios y Hospedajes Web",
        titleH3: "",
        contents: "",
        notas: "[squarespace.com]",
        group: []
    },
    {
        id: "10",
        category: "Portafolio",
        linkHref: "",
        targetType : "",
        imgSrc: "../public/images/portafolio-code-r11.png",
        titleH2: "Portafolio",
        titleH3: "",
        contents: "",
        nota: "Crea tu portafolio de una manera profesional.",
        group: []
    },
    {
        id: "11",
        category: "Trabajos-Remotos",
        linkHref: "trabajos-remotos.html",
        targetType : "",
        imgSrc: "../public/images/TrabajosRemotos.png",
        titleH2: "Proyectos y Trabajos Remotos",
        titleH3: "",
        contents: "",
        group: [
            {
                linkHref: "trabajos-remotos.html",
                targetType : "",
                imgSrc: "https://yt3.ggpht.com/dW6to0x5Crmeh7yi-YPLcQRqVrBtx2BSh8eoKTJbE8NbjloQ0sqlmdszIlxokJU_97-ndOt_=s900-c-k-c0x00ffffff-no-rj",
                titleH2: "ARC()",
                titleH3: "Inglés",
                contents: "Búsqueda de trabajo a distancia",
            },
            {
                linkHref: "trabajos-remotos.html",
                targetType : "",
                imgSrc: "https://miro.medium.com/max/1400/1*aTYOTFS4Vkr-nwHNML3GvQ.jpeg",
                titleH2: "Otra",
                titleH3: "Inglés",
                contents: "Búsqueda de trabajo a distanciadonde. ",
            }
        ]
    },
    {
        id: "12",
        category: "Code-R11",
        linkHref: "../page/proyecto-code-r11.html",
        targetType : "",
        imgSrc: "../public/images/coder11.jpg",
        titleH2: "Ruta de Aprendizaje y Plan de Estudio Code R11",
        titleH3: "",
        contents: "",
        group: []
    },
];



